name: smart_tel
description: Smart and Remote Control of Surrounding Devices 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  flutter_zoom_drawer: ^2.3.1+1
  dio: ^4.0.4
  provider: ^6.0.2
  flutter_switch: ^0.3.2
  string_validator: ^0.3.0
  url_launcher: ^6.0.20
  connectivity_plus: ^2.2.1
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  convex_bottom_bar: ^3.0.0
  shared_preferences: ^2.0.13
  arp_scanner: ^1.2.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - images/
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

